---
- name: Initial ubuntu hardening
  hosts: ubuntu
  become: true
  
  tasks:

  - name: Update installed packages
    ansible.builtin.apt:
      name: "*"
      update_cache: true
      state: latest
    notify: Reboot servers
  
  - name: UFW is installed
    ansible.builtin.apt:
      name: ufw
      state: present
  
  - name: Reset UFW to default
    community.general.ufw:
      state: reset

  - name: Define outgoing connection policy
    community.general.ufw:
      direction: outgoing
      policy: allow

  - name: Definde ingoing connection policy
    community.general.ufw:
      direction: incoming
      policy: deny

  - name: Allow ssh connections and enable UFW
    community.general.ufw:
      name: OpenSSH
      rule: allow
      state: enabled

  - name: fail2ban is installed
    ansible.builtin.apt:
      name: fail2ban
      state: present

  - name: Copy jail.local config
    ansible.builtin.copy:
      src: ./files/jail.local
      dest: /etc/fail2ban/jail.local
      mode: '0600'
      owner: root
      group: root
    notify: Restart fail2ban

  - name: fail2ban started and enabled
    ansible.builtin.systemd_service:
      name: fail2ban
      state: started
      enabled: true


  handlers:

  - name: Reboot servers
    ansible.builtin.reboot:
      reboot_timeout: 300

  - name: Restart fail2ban
    ansible.builtin.systemd_service:
      name: fail2ban
      state: restarted
